service: s3-file-uploader
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1

custom:
  fileUploadBucketName: ${self:custom.fileUploadBucketName}

resources:
  Resources:
    fileBucket:
      Type : AWS::s3::Bucket
      Properties:
        BucketName: ${self:custom.fileUploadBucketName}
        AccessControl : PublicRead